import type { Metadata } from "next";
import { prompt, poppins } from "@/lib/fonts";
import "./styles/globals.css";
import "./styles/animate.css";
import Header from "@/components/layout/MiniHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="th">
      <body suppressHydrationWarning className={`${prompt.variable} ${poppins.variable} font-sans`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
